---
title: "Deadbiomass"
author: "Samantha Hing"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
# load packages
library(raster)
library(sf)
library(ggplot2)

```

```{r}
# load previous files
#rmarkdown::render('./FireDBR_calcs.Rmd') # gives us dbr dataframe ("dbr_data") & rasterList

# download dead biomass tif file
dead_biomass <- raster("../data/DeadBiomass110.tif") # you have to download this file onto your personal computer (not on git)

# read 110 fire shapefile
fire_polygons <- st_read('data/fire_data/110fires_sample.shp') # fire polygons

```


```{r}
# Need to crop dead biomass file by each fire polygon

# store fire polygon geometry separately
fire_polygons_geom <- st_geometry(fire_polygons)
names(fire_polygons_geom) <- fire_polygons$OBJECTID
#$geometry

# match fire projection to dead biomass projection
fires_projected <- st_transform(fire_polygons_geom, crs(dead_biomass))

# check CRS's match
st_crs(fires_projected)
crs(dead_biomass)

# for one fire = delete later
extent <- as_Spatial(fires_projected[1])
dead_biomass_1 <- crop(x = dead_biomass, y = extent)

# check that it worked
plot(dead_biomass1)
plot(fire1_proj)
plot(rasterList$`20500`)

# crop dead biomass for all fires
dead_biomassList <- list() # initialize empty list
for (i in 1:length(fires_projected)) {
  extent <- as_Spatial(fires_projected[i])
  dead_biomassList[[i]] <- crop(x = dead_biomass, y = extent)
}

# name the dead_biomass list by Object IDs
names(dead_biomassList) <- fire_polygons$OBJECTID

# check a few
plot(dead_biomassList[[100]])
plot(fires_projected[100])
```



