---
title: "ShinyApp"
author: "Samantha Hing"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(leaflet)
library(shiny)
library(shinythemes)
library(tidyverse)
library(raster)

```

### Run these files first
```{r}
# Run these files to get data frames
# Maybe we should turn them into .R files instead?
# rmarkdown::render('./ClimateStations_RAWS.Rmd') # gives us weather dataframe ("fires_weather")
# rmarkdown::render('./FireDBR_calcs.Rmd') # gives us dbr dataframe ("dbr_data")
rmarkdown::render('./Cropping_biomass&vegtype&treedens.Rmd') # gives us list of dead & live biomass rasters ("live_biomassList" & "dead_biomassList") and vegtype rasters ("veg_typeList"), and tree density rasters ("tree_densityList")
rmarkdown::render('./regression_model2.Rmd') # gives us dataframes: fires_weather, ave_data, dbr_data

# name rasters by ObjectID
names(rasterList) <- OBJECTID 

#average_data <- read_csv("data/ave_export_sum.csv") # gives average data





```
# data prep
```{r}
# get centroid of fires
fires <- fires %>%
  mutate(centroids = st_centroid(geometry))
fires_points <- fires$centroids
fires_points <- st_transform(fires_points, 4326)
fires_points <- as.data.frame(st_coordinates(fires_points))
fires_points <- fires_points %>% mutate(OBJECTID = as.character(fires$OBJECTID))

ave_data2 <- ave_data %>% 
  mutate(OBJECTID = as.character(OBJECTID)) %>%
  full_join(fires_points, by = 'OBJECTID') %>%
  mutate(startdate = format(as.Date(ALARM_DATE), format = "%B %d")) %>%
  mutate(enddate = format(as.Date(CONT_DATE), format = "%B %d")) %>%
  filter(!is.na(DEM_MEAN)) %>%
  filter(!is.na(dbr_means)) %>%
  filter(!is.na(wind_speed)) %>%
  filter(!is.na(wind_max)) %>%
  distinct(OBJECTID, .keep_all = TRUE)


```

# Make fire icon for leaflet map
```{r}
fireIcon <-makeIcon(
  "./graphics/icons8-fire-48.png",
  iconWidth = 28, iconHeight = 28
)

```


# User Interface
```{r}
ui <- fluidPage (
  navbarPage("DS421 Project",
  #titlePanel("California Wildfires 2017"), #make better title later
  theme = shinythemes::shinytheme('simplex'),
  tabPanel("About",
     fluidRow(column(4, p("Summary of Fires"), plotOutput('piechart')))
  ),
  tabPanel("Fire Data",
      # selectInput('results', 'Pick Results to See', choices = c('DBR', 'dead biomass', 'live biomass')),
    fluidRow(
      column(6, p("Burn Severity for Selected Fire"), leaflet::leafletOutput('dbr_map')),
      column(6, p("California Wildfires in 2017"), leaflet::leafletOutput('map', width = '100%')) # add CA map
    ),
    fluidRow(
      column(3, p("Live biomass"), leaflet::leafletOutput('livebiomass_map')), # live biomass map
      column(3, p("Dead biomass"), leaflet::leafletOutput('deadbiomass_map')), # dead biomass map
      column(3, p("Tree density"), leaflet::leafletOutput('treedensity_map')), # tree density map
      column(3, p("Land cover type"), leaflet::leafletOutput('vegtype_map'))
    ),
    fluidRow(
      column(12, p("Weather parameters"), tableOutput(outputId = "table")) # weather table
    )
  ),
    
 
  tabPanel("Model Results")
  
  )
)

```

# Server
```{r}
server <- function(input, output, session) {
 
  # create map of California with a marker for each fire
  output$map <- leaflet::renderLeaflet({
    leaflet(
      options = leafletOptions(zoomControl = FALSE,
                     dragging = FALSE)) %>% 
      addTiles() %>% # Add default OpenStreetMap map tiles
      addProviderTiles("Esri.WorldImagery") %>%
      addMarkers(lat = ave_data2$Y, lng = ave_data2$X, 
                 layerId = ave_data2$OBJECTID, 
                 icon = fireIcon,
                 popup = paste(ave_data2$FIRE_NAME, "Fire", "<br>",
                               "Dates:", ave_data2$startdate, "-", ave_data2$enddate, "<br>",
                               "Fire Size:", round(ave_data2$GIS_ACRES), "acres", "<br>",
                               "Average Burn Severity:", ave_data2$mean_severityClass))
      })
  
  # pie chart output
  output$piechart <- renderPlot({
    ave_data2 %>%
    count(mean_severityClass) %>% 
    ggplot(aes(x = "", y = n, fill = mean_severityClass)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_manual(values = c("darkgreen", "forestgreen", "limegreen", "yellow", "orange", "orangered", "purple")) +
    theme(legend.title = element_blank()) +
    labs(title = "Proportion of total fires by average burn severity")

  })
  
  # show image
    # fire_chosen <- reactive({input$fires})
    # output$dbr_plot <- renderPlot(rasterList$`fire_chosen`)
    # #renderImage()
    # output$dbr_map <- renderLeaflet({
    #   leaflet() %>% 
    #     addTiles %>% 
    #     addRasterImage(fire_chosen()) 
    # })
  
  # define legend inputs for DBR maps
  colorsDBR = c("darkgreen", "forestgreen", "limegreen", "yellow", "orange", "orangered", "purple")
  binsDBR = c(-1000, -251, -101, 99, 269, 439, 659, 2000)
  paletteDBR <- colorBin(palette = colorsDBR, bins = binsDBR, domain = binsDBR, na.color = "transparent")
  labelsDBR = c("Enhanced Regrowth, High", "Enhanced Regrowth, Low", "Unburned", "Low Severity", "Modereat-Low Severity", "Moderate-High Severity", "High Severity")

 
    observeEvent(input$map_marker_click, {
      # user clicks fire
      click <- input$map_marker_click
    
      # DBR map
      fire_chosen <- reactive({rasterList[[click$id]]})
      
      output$dbr_map <- renderLeaflet({
      leaflet() %>% 
        addTiles %>% 
        addProviderTiles("Esri.WorldImagery") %>%
        addRasterImage(fire_chosen(), colors = paletteDBR, opacity = 0.8) %>%
        addLegend(position = "bottomleft",
                  pal = paletteDBR,
                  values = binsDBR,
                  opacity = 0.7,
                  title = "dNBR Classes",
                  labFormat = function(type, cuts, p) {
                    paste0(labelsDBR)
                  }
        )
      })
      
      # Live Biomass Map
      # live biomass raster for selected fire
      livebiomass_fire <- reactive({live_biomassList[[click$id]]})
       
      # define legend inputs for live biomass maps
      domainLB <- cellStats(livebiomass_fire(), "range")
      paletteLB <- colorNumeric("Greens", domain = domainLB, na.color = "transparent")
  

      output$livebiomass_map <- renderLeaflet({
      leaflet() %>% 
        addTiles %>% 
        addProviderTiles("Esri.WorldImagery") %>%
        addRasterImage(livebiomass_fire(), colors = paletteLB, opacity = 1) %>%
        addLegend(position = "bottomleft",
                  pal = paletteLB,
                  values = domainLB, 
                  opacity = 0.7,
                  title = "live biomass (kg/ha)")
      })
      
      # Dead Biomass Map
      # dead biomass raster for selected fire
      deadbiomass_fire <- reactive({dead_biomassList[[click$id]]})

      # define legend inputs for live biomass maps
      domainDB <- cellStats(deadbiomass_fire(), "range")
      paletteDB <- colorNumeric("YlOrBr", domain = domainDB, na.color = "transparent")


      output$deadbiomass_map <- renderLeaflet({
      leaflet() %>%
        addTiles %>%
        addProviderTiles("Esri.WorldImagery") %>%
        addRasterImage(deadbiomass_fire(), colors = paletteDB, opacity = 1) %>%
        addLegend(position = "bottomleft",
                  pal = paletteDB,
                  values = domainDB,
                  opacity = 0.7,
                  title = "dead biomass (kg/ha)")
      })

      # Tree Density Map
      # tree density raster for selected fire
      treedensity_fire <- reactive({tree_densityList[[click$id]]})

      # define legend inputs for live biomass maps
      domainTD <- cellStats(treedensity_fire(), "range")
      #domainTD <- c(0, 11000)
      paletteTD <- colorNumeric("RdPu", domain = domainTD, na.color = "transparent")


      output$treedensity_map <- renderLeaflet({
      leaflet() %>%
      addTiles %>%
      addProviderTiles("Esri.WorldImagery") %>%
        addRasterImage(treedensity_fire(), colors = paletteTD, opacity = 1, maxBytes = Inf, project = FALSE) %>%
        addLegend(position = "bottomleft",
                  pal = paletteTD,
                  values = domainTD,
                  opacity = 0.7,
                  title = "tree density (#/ha)")
      })

      # Veg Type Map
      # veg type raster for selected fire
      vegtype_fire <- reactive({veg_typeList[[click$id]]})

      # define legend inputs for veg type maps
      colorsVT = c("darkgreen", "deeppink", "darkorchid", "gold", "red", "orange", "cyan", "green")
      levelsVT = c(1, 2, 3, 4, 5, 6, 7, 8)
      labelsVT = c("conifer", "shrub", "herbaceous", "barren-other", "urban", "hardwood", "water", "agricultural")
      paletteVT <- colorFactor(palette = colorsVT, levels = levelsVT, na.color = "transparent")
      
      output$vegtype_map <- renderLeaflet({
      leaflet() %>%
      addTiles %>%
      addProviderTiles("Esri.WorldImagery") %>%
        addRasterImage(vegtype_fire(), colors = paletteVT, opacity = 1, maxBytes = Inf, project = FALSE) %>%
        addLegend(position = "bottomleft",
                  pal = paletteVT,
                  values = levelsVT,
                  opacity = 0.7,
                  title = "land cover type",
                  labFormat = function(type, cuts, p) {
                    paste0(labelsVT)
                  }
        )
      })
      
      # Summary Table
      # create table for average weather data for each fire
        output$table <- renderTable({
          ave_data2 %>%
            filter(FIREID == click$id) %>%
            dplyr::select(month_temp, 
                          week_temp, 
                          month_precip, 
                          week_precip,
                          wind_speed, 
                          wind_max, 
                          month_humid, 
                          week_humid) %>%
            dplyr::rename(
              "Prior month avg temp (F)" = month_temp, 
              "Prior week mavg temp (F)" = week_temp, 
              "Prior month avg precip (in)" = month_precip, 
              "Prior week avg precip (in)" = week_precip, 
              "Avg wind speed during (mph)" = wind_speed, 
              "Avg max wind speed during (mph)" = wind_max, 
              "Prior month avg humidity (%)" = month_humid, 
              "Prior week avg humidity (%)" = week_humid)
              
          
        })

      })
 
  
}


```

# Run Shiny
```{r}
shinyApp(ui = ui, server = server)


```